server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: postgres
    password: postgres

mybatis:
  mapper-locations:
    - classpath:dao/*.xml

logging:
  level:
    root: info
    com.macro.mall: debug